<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'sun right'     => 'Spring',
    'sun top'       => 'Summer',
    'sun left'      => 'Autumn',
    'sun bottom'    => 'Winter',
    'moon right'    => 'Growing',
    'moon top'      => 'Full',
    'moon left'     => 'Warming',
    'moon bottom'   => 'New',
    'earth right'   => 'Morning',
    'earth top'     => 'Day',
    'earth left'    => 'Evening',
    'earth bottom'  => 'Night',
    'Admin' => '',
    'Login' => '',
    'Powered by' => '',
    'Are you sure you want to delete this item?' => '',
    'Cannot delete default!' => '',
    'Choose your language' => '',
    'Code' => '',
    'Control' => '',
    'Content' => '',
    'Create Cycle' => '',
    'Create Element' => '',
    'Create Lair' => '',
    'Create Language' => '',
    'Create Spoke' => '',
    'Created At' => '',
    'Cycle' => '',
    'Cycles' => '',
    'Delete' => '',
    'Description' => '',
    'Direction' => '',
    'Element' => '',
    'Elements' => '',
    'English' => '',
    'ID' => '',
    'Icon' => '',
    'Lairs' => '',
    'Language' => '',
    'Languages' => '',
    'Media' => '',
    'Name' => '',
    'Native Name' => '',
    'Owner' => '',
    'Period' => '',
    'Reset' => '',
    'Russian' => '',
    'Save' => '',
    'Search' => '',
    'Select cycle' => '',
    'Select element' => '',
    'Select language' => '',
    'Select spoke' => '',
    'Signup' => '',
    'Spoke' => '',
    'Spokes' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Cycle: {name}' => '',
    'Update Element: {name}' => '',
    'Update Lair: {name}' => '',
    'Update Language: {name}' => '',
    'Update Spoke: {name}' => '',
    'Updated At' => ''
];
