<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Домой',
    'Login' => 'Логин',
    'Powered by' => 'Создано',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить этот элемент?',
    'Cannot delete default!' => 'Невозможно удалить элемент по умолчанию!',
    'Choose your language' => 'Выберите ваш язык',
    'Code' => 'Код',
    'Create Cycle' => 'Создать цикл',
    'Create Element' => 'Создать стихию',
    'Create Lair' => 'Создать дом',
    'Create Language' => 'Создать язык',
    'Create Spoke' => 'Создать спицу',
    'Created At' => 'Создано',
    'Cycle' => 'Цикл',
    'Cycles' => 'Циклы',
    'Delete' => 'Удалить',
    'Desc' => 'Описание',
    'Direction' => 'Направление',
    'Element' => 'Стихия',
    'Elements' => 'Стихии',
    'English' => 'Англайский',
    'ID' => 'ID',
    'Icon' => 'Иконка',
    'Lairs' => 'Дома',
    'Language' => 'Язык',
    'Languages' => 'Языки',
    'Name' => 'Имя',
    'Native Name' => 'Самоназвание',
    'Owner' => 'Владелец',
    'Period' => 'Период',
    'Reset' => 'Сбросить',
    'Russian' => 'Русский',
    'Save' => 'Сохранить',
    'Search' => 'Искать',
    'Select cycle' => 'Выберите цикл...',
    'Select element' => 'Выберите стихию',
    'Select language' => 'Выберите язык',
    'Select spoke' => 'Выберите спицу',
    'Spoke' => 'Спица',
    'Spokes' => 'Спицы',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Update' => 'Обновить',
    'Update Cycle: {name}' => 'Обновить цикл: {name}',
    'Update Element: {name}' => 'Обновить стихию: {name}',
    'Update Lair: {name}' => 'Обновить дом: {name}',
    'Update Language: {name}' => 'Обновить язык: {name}',
    'Update Spoke: {name}' => 'Обновить спицу',
    'Updated At' => 'Обновлено'
];
